---
title: Nothing Rhymes with Orange
timezone: America/Los_Angeles
collections:
  contacts:
    title: Contacts
    output: true
  posts:
    title: Posts
    output: true
  representatives:
    title: Representatives
    output: false
  successes:
    title: Successes
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    is featured: false
    main-image: 
    call-script-text: 
    event-start-date: 
    event-end-date: 
    Location: 
    RSVP-link: 
    layout: post
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: representatives
  values:
    phone-numbers:
      office-name: "(000) 000-0000"
    website: 
- scope:
    path: ''
    type: successes
  values:
    is featured: false
    main-image: 
    layout: media-item
- scope:
    path: ''
    type: calendar
  values:
    embed-code: 
- scope:
    path: ''
    type: becomeAMember
  values:
    main-image: 
    mailchimp-form-embed: 
subtitle: Welcome, Nothing Rhymes with Orange Warriors!
email: sasilve2002@gmail.com
baseurl: 
url: 
twitter_username: 
facebook_username: indivisibleguide
background-image: "/uploads/CC%20signs%20in%20window.jpg"
member-count: 24
footer-title: The best way to support our democracy is to participate.  Join us to
  help flip districts and to  support California's sanctuary status.  We can do this
  together.   Welcome !
markdown: kramdown
gems:
- jekyll-feed
- jekyll-paginate
paginate: 10
paginate_path: "/blog/page:num/"
exclude:
- Gemfile
- Gemfile.lock
google_analytics: 
